// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference path="bakks/nitro.d.ts" />
/// <reference types="nuxt3" />
/// <reference path="bakks/components.d.ts" />
/// <reference path="bakks/auto-imports.d.ts" />
export {}
